version: "3.8"
services:
  ocr-tts-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./secrets.yaml:/app/secrets.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
    restart: unless-stopped
