version: "3.9"
services:
  app:
    build: .
    container_name: fastapi-tts-gpu
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./secrets.yaml:/app/secrets.yaml:ro    
    environment:
      - CONFIG_PATH=/app/config.yaml